# Form implementation generated from reading ui file 'pageinsereitem.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindowIsertBox(object):
    def setupUi(self, MainWindowIsertBox):
        MainWindowIsertBox.setObjectName("MainWindowIsertBox")
        MainWindowIsertBox.resize(404, 140)
        MainWindowIsertBox.setMinimumSize(QtCore.QSize(404, 140))
        MainWindowIsertBox.setMaximumSize(QtCore.QSize(404, 140))
        MainWindowIsertBox.setStyleSheet("background-color: rgb(32, 32, 35);")
        self.centralwidgetInsertBox = QtWidgets.QWidget(MainWindowIsertBox)
        self.centralwidgetInsertBox.setObjectName("centralwidgetInsertBox")
        self.label_26 = QtWidgets.QLabel(self.centralwidgetInsertBox)
        self.label_26.setGeometry(QtCore.QRect(4, 1, 201, 21))
        self.label_26.setStyleSheet("color: rgb(234, 234, 234);\n"
"font: 10pt \"Segoe UI\";\n"
"background-color: none;")
        self.label_26.setObjectName("label_26")
        self.inserir_item_no_combobox = QtWidgets.QLineEdit(self.centralwidgetInsertBox)
        self.inserir_item_no_combobox.setGeometry(QtCore.QRect(4, 31, 391, 31))
        self.inserir_item_no_combobox.setStyleSheet("background-color: rgb(32, 32, 35);\n"
"color: rgb(255, 255, 255);\n"
"border: none;")
        self.inserir_item_no_combobox.setClearButtonEnabled(True)
        self.inserir_item_no_combobox.setObjectName("inserir_item_no_combobox")
        self.widget_3 = QtWidgets.QWidget(self.centralwidgetInsertBox)
        self.widget_3.setGeometry(QtCore.QRect(4, 61, 391, 2))
        self.widget_3.setStyleSheet("background-color: rgb(251, 211, 141);")
        self.widget_3.setObjectName("widget_3")
        self.botao_inserir_database_prazo = QtWidgets.QPushButton(self.centralwidgetInsertBox)
        self.botao_inserir_database_prazo.setGeometry(QtCore.QRect(4, 111, 75, 24))
        self.botao_inserir_database_prazo.setStyleSheet("QPushButton:hover{\n"
"    background-color: #f6ad55;\n"
"    border: 5px solid #f6ad55;\n"
"    color: rgb(32, 32, 35);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"   color: rgb(32, 32, 35);\n"
"   border-radius: 5px;\n"
"   background-color: rgb(251, 211, 141);\n"
"}")
        self.botao_inserir_database_prazo.setObjectName("botao_inserir_database_prazo")
        self.botao_inserir_database_frete = QtWidgets.QPushButton(self.centralwidgetInsertBox)
        self.botao_inserir_database_frete.setGeometry(QtCore.QRect(84, 111, 75, 24))
        self.botao_inserir_database_frete.setStyleSheet("QPushButton:hover{\n"
"    background-color: #f6ad55;\n"
"    border: 5px solid #f6ad55;\n"
"    color: rgb(32, 32, 35);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"   color: rgb(32, 32, 35);\n"
"   border-radius: 5px;\n"
"   background-color: rgb(251, 211, 141);\n"
"}")
        self.botao_inserir_database_frete.setObjectName("botao_inserir_database_frete")
        self.botao_inserir_database_produto = QtWidgets.QPushButton(self.centralwidgetInsertBox)
        self.botao_inserir_database_produto.setGeometry(QtCore.QRect(164, 111, 75, 24))
        self.botao_inserir_database_produto.setStyleSheet("QPushButton:hover{\n"
"    background-color: #f6ad55;\n"
"    border: 5px solid #f6ad55;\n"
"    color: rgb(32, 32, 35);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"   color: rgb(32, 32, 35);\n"
"   border-radius: 5px;\n"
"   background-color: rgb(251, 211, 141);\n"
"}")
        self.botao_inserir_database_produto.setObjectName("botao_inserir_database_produto")
        self.botao_inserir_database_transporte = QtWidgets.QPushButton(self.centralwidgetInsertBox)
        self.botao_inserir_database_transporte.setGeometry(QtCore.QRect(244, 111, 75, 24))
        self.botao_inserir_database_transporte.setStyleSheet("QPushButton:hover{\n"
"    background-color: #f6ad55;\n"
"    border: 5px solid #f6ad55;\n"
"    color: rgb(32, 32, 35);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"   color: rgb(32, 32, 35);\n"
"   border-radius: 5px;\n"
"   background-color: rgb(251, 211, 141);\n"
"}")
        self.botao_inserir_database_transporte.setObjectName("botao_inserir_database_transporte")
        self.botao_inserir_database_vendedor = QtWidgets.QPushButton(self.centralwidgetInsertBox)
        self.botao_inserir_database_vendedor.setGeometry(QtCore.QRect(324, 111, 75, 24))
        self.botao_inserir_database_vendedor.setStyleSheet("QPushButton:hover{\n"
"    background-color: #f6ad55;\n"
"    border: 5px solid #f6ad55;\n"
"    color: rgb(32, 32, 35);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"   color: rgb(32, 32, 35);\n"
"   border-radius: 5px;\n"
"   background-color: rgb(251, 211, 141);\n"
"}")
        self.botao_inserir_database_vendedor.setObjectName("botao_inserir_database_vendedor")
        self.label_27 = QtWidgets.QLabel(self.centralwidgetInsertBox)
        self.label_27.setGeometry(QtCore.QRect(4, 81, 281, 21))
        self.label_27.setStyleSheet("color: rgb(234, 234, 234);\n"
"font: 10pt \"Segoe UI\";\n"
"background-color: none;")
        self.label_27.setObjectName("label_27")
        MainWindowIsertBox.setCentralWidget(self.centralwidgetInsertBox)

        self.retranslateUi(MainWindowIsertBox)
        QtCore.QMetaObject.connectSlotsByName(MainWindowIsertBox)

    def retranslateUi(self, MainWindowIsertBox):
        _translate = QtCore.QCoreApplication.translate
        MainWindowIsertBox.setWindowTitle(_translate("MainWindowIsertBox", "Cadastrar"))
        MainWindowIsertBox.setWindowIcon(QtGui.QIcon('icons\\footprint.ico'))
        self.label_26.setText(_translate("MainWindowIsertBox", "Insira o item que deseja adicionar"))
        self.botao_inserir_database_prazo.setText(_translate("MainWindowIsertBox", "prazo"))
        self.botao_inserir_database_frete.setText(_translate("MainWindowIsertBox", "frete"))
        self.botao_inserir_database_produto.setText(_translate("MainWindowIsertBox", "produto"))
        self.botao_inserir_database_transporte.setText(_translate("MainWindowIsertBox", "transporte"))
        self.botao_inserir_database_vendedor.setText(_translate("MainWindowIsertBox", "vendedor"))
        self.label_27.setText(_translate("MainWindowIsertBox", "SELECIONE ONDE DESEJA ADICIONAR O ITEM!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowIsertBox = QtWidgets.QMainWindow()
    ui = Ui_MainWindowIsertBox()
    ui.setupUi(MainWindowIsertBox)
    MainWindowIsertBox.show()
    sys.exit(app.exec())
