# Form implementation generated from reading ui file 'deleteitem.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindowDeleteBox(object):
    def setupUi(self, MainWindowDeleteBox):
        MainWindowDeleteBox.setObjectName("MainWindowDeleteBox")
        MainWindowDeleteBox.resize(404, 140)
        MainWindowDeleteBox.setMinimumSize(QtCore.QSize(404, 140))
        MainWindowDeleteBox.setMaximumSize(QtCore.QSize(404, 140))
        MainWindowDeleteBox.setStyleSheet("background-color: rgb(32, 32, 35);")
        self.centralwidget = QtWidgets.QWidget(MainWindowDeleteBox)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_item_delete = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_item_delete.setGeometry(QtCore.QRect(4, 42, 391, 21))
        self.comboBox_item_delete.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-radius: 5px;")
        self.comboBox_item_delete.setObjectName("comboBox_item_delete")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(4, 2, 211, 21))
        self.label_28.setStyleSheet("color: rgb(234, 234, 234);\n"
"font: 10pt \"Segoe UI\";\n"
"background-color: none;")
        self.label_28.setObjectName("label_28")
        self.botao_excluir_prazo = QtWidgets.QPushButton(self.centralwidget)
        self.botao_excluir_prazo.setGeometry(QtCore.QRect(4, 112, 75, 24))
        self.botao_excluir_prazo.setStyleSheet("QPushButton:hover{\n"
"    background-color: #f6ad55;\n"
"    border: 5px solid #f6ad55;\n"
"    color: rgb(32, 32, 35);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"   color: rgb(32, 32, 35);\n"
"   border-radius: 5px;\n"
"   background-color: rgb(251, 211, 141);\n"
"}")
        self.botao_excluir_prazo.setObjectName("botao_excluir_prazo")
        self.botao_excluir_frete = QtWidgets.QPushButton(self.centralwidget)
        self.botao_excluir_frete.setGeometry(QtCore.QRect(84, 112, 75, 24))
        self.botao_excluir_frete.setStyleSheet("QPushButton:hover{\n"
"    background-color: #f6ad55;\n"
"    border: 5px solid #f6ad55;\n"
"    color: rgb(32, 32, 35);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"   color: rgb(32, 32, 35);\n"
"   border-radius: 5px;\n"
"   background-color: rgb(251, 211, 141);\n"
"}")
        self.botao_excluir_frete.setObjectName("botao_excluir_frete")
        self.botao_excluir_produto = QtWidgets.QPushButton(self.centralwidget)
        self.botao_excluir_produto.setGeometry(QtCore.QRect(164, 112, 75, 24))
        self.botao_excluir_produto.setStyleSheet("QPushButton:hover{\n"
"    background-color: #f6ad55;\n"
"    border: 5px solid #f6ad55;\n"
"    color: rgb(32, 32, 35);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"   color: rgb(32, 32, 35);\n"
"   border-radius: 5px;\n"
"   background-color: rgb(251, 211, 141);\n"
"}")
        self.botao_excluir_produto.setObjectName("botao_excluir_produto")
        self.botao_excluir_transporte = QtWidgets.QPushButton(self.centralwidget)
        self.botao_excluir_transporte.setGeometry(QtCore.QRect(244, 112, 75, 24))
        self.botao_excluir_transporte.setStyleSheet("QPushButton:hover{\n"
"    background-color: #f6ad55;\n"
"    border: 5px solid #f6ad55;\n"
"    color: rgb(32, 32, 35);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"   color: rgb(32, 32, 35);\n"
"   border-radius: 5px;\n"
"   background-color: rgb(251, 211, 141);\n"
"}")
        self.botao_excluir_transporte.setObjectName("botao_excluir_transporte")
        self.botao_excluir_vendedor = QtWidgets.QPushButton(self.centralwidget)
        self.botao_excluir_vendedor.setGeometry(QtCore.QRect(324, 112, 75, 24))
        self.botao_excluir_vendedor.setStyleSheet("QPushButton:hover{\n"
"    background-color: #f6ad55;\n"
"    border: 5px solid #f6ad55;\n"
"    color: rgb(32, 32, 35);\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton {\n"
"   color: rgb(32, 32, 35);\n"
"   border-radius: 5px;\n"
"   background-color: rgb(251, 211, 141);\n"
"}")
        self.botao_excluir_vendedor.setObjectName("botao_excluir_vendedor")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(4, 82, 261, 21))
        self.label_29.setStyleSheet("color: rgb(234, 234, 234);\n"
"font: 10pt \"Segoe UI\";\n"
"background-color: none;")
        self.label_29.setObjectName("label_29")
        MainWindowDeleteBox.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindowDeleteBox)
        QtCore.QMetaObject.connectSlotsByName(MainWindowDeleteBox)

    def retranslateUi(self, MainWindowDeleteBox):
        _translate = QtCore.QCoreApplication.translate
        MainWindowDeleteBox.setWindowTitle(_translate("MainWindowDeleteBox", "Deletar Item"))
        MainWindowDeleteBox.setWindowIcon(QtGui.QIcon('icons\\footprint.ico'))
        self.label_28.setText(_translate("MainWindowDeleteBox", "Selecione o item que deseja excluir"))
        self.botao_excluir_prazo.setToolTip(_translate("MainWindowDeleteBox", "excluir item em prazo"))
        self.botao_excluir_prazo.setText(_translate("MainWindowDeleteBox", "prazo"))
        self.botao_excluir_frete.setToolTip(_translate("MainWindowDeleteBox", "excluir item em frete"))
        self.botao_excluir_frete.setText(_translate("MainWindowDeleteBox", "frete"))
        self.botao_excluir_produto.setToolTip(_translate("MainWindowDeleteBox", "excluir item em produto"))
        self.botao_excluir_produto.setText(_translate("MainWindowDeleteBox", "produto"))
        self.botao_excluir_transporte.setToolTip(_translate("MainWindowDeleteBox", "excluir item em transporte"))
        self.botao_excluir_transporte.setText(_translate("MainWindowDeleteBox", "transporte"))
        self.botao_excluir_vendedor.setToolTip(_translate("MainWindowDeleteBox", "excluir item em vendedor"))
        self.botao_excluir_vendedor.setText(_translate("MainWindowDeleteBox", "vendedor"))
        self.label_29.setText(_translate("MainWindowDeleteBox", "SELECIONE ONDE DESEJA EXCLUIR O ITEM!"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindowDeleteBox = QtWidgets.QMainWindow()
    ui = Ui_MainWindowDeleteBox()
    ui.setupUi(MainWindowDeleteBox)
    MainWindowDeleteBox.show()
    sys.exit(app.exec())
